language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package=lib

after_success:
  - coveralls
